export class CustomerInfo {
	cuiNum : number;
	cuiName : string;
	cuiNickname : string;
	cuiMobilePhone : string;
	cuiHomePhone : string;
	cuiTrans : string;
	cuiBirth : string;
	cuiProfileimgName : string;
	cuiProfileimg : File;
	cuiAgreeLocation : string;
	cuiAgreeLocationdat : string;
	cuiAgreePhone : string;
	cuiAgreePhonedat : string;
	cuiAgreeCamera : string;
	cuiAgreeCameradat : string;
	cuiAgreePush : string;
	cuiAgreePushdat : string;
	cuiAgreeSms : string;
	cuiAgreeSmsdat : string;
	cuiAgreeEmail : string;
	cuiAgreeEmaildat : string;
	cuiAgreeService : string;
	cuiAgreeServicedat : string;
	cuiAgreePrivate : string;
	cuiAgreePrivatedat : string;
	credat : string;
	cretim : string;
	creusr : number;
	moddat : string;
	modtim : string;
	modusr : number;
	active : string='1';
	orders:string;
}
