export class ShopInfo {
	shiNum : number;
	shiName : string;
	shiSname : string;
	shiZip : string;
	shiAddr : string;
	shiSubaddr : string;
	shiAddrDesc : string;
	shiGox : string;
	shiGoy : string;
	shiMobilePhone : string;
	shiOfficePhone : string;
	shiWorkDay : string;
	shiHollyDay : string;
	shiWorkTime : string;
	shiLunchTime : string;
	shiLink : string;
	shiBizName : string;
	shiBizNum : string;
	shiBizOwner : string;
	shiBizBiz : string;
	shiBizSector : string;
	shiBizDoc : string;
	shiBizIssuer : string;
	shiBizIssdat : string;
	shiBizType : string;
	shiReportNum : string;
	credat : string;
	cretim : string;
	creusr : number;
	moddat : string;
	modtim : string;
	modusr : number;
	active : string='1';
	orders:string;
}
